import os

# Python script to generate the "classpath.sh" file from the list
# of jar files in the lib/ directory.
#
# Chris Joakim, 2016/04/20
#
# Usage:
# $ python classpath.py > classpath.sh

def include_jar(base_name):
    if 'sources.jar' in base_name:
        return False
    if 'javadoc.jar' in base_name:
        return False
    if base_name.endswith('.jar'):
        return True
    else:
        return False

if __name__ == "__main__":
    print('#!/bin/bash')
    print('')
    print('# classpath bash script generated by classpath.py,')
    print('# and can be sourced by other bash scripts.')
    print('# Chris Joakim, 2016/04/20')
    print('')
    print('CLASSPATH=$CLASSPATH:svcbus.jar')
    print('')
    for dir_name, subdirs, base_names in os.walk('lib'):
        for base_name in base_names:
            if include_jar(base_name):
                print("CLASSPATH=$CLASSPATH:lib/{0}".format(base_name))
        print('')
        print('export CLASSPATH')
        print('')
