#!/bin/bash

# classpath bash script generated by classpath.py,
# and can be sourced by other bash scripts.
# Chris Joakim, 2016/04/20

CLASSPATH=$CLASSPATH:svcbus.jar

CLASSPATH=$CLASSPATH:lib/activation-1.1.jar
CLASSPATH=$CLASSPATH:lib/adal4j-1.0.0.jar
CLASSPATH=$CLASSPATH:lib/avalon-framework-4.1.5.jar
CLASSPATH=$CLASSPATH:lib/azure-core-0.9.2.jar
CLASSPATH=$CLASSPATH:lib/azure-documentdb-0.9.2.jar
CLASSPATH=$CLASSPATH:lib/azure-keyvault-0.9.2.jar
CLASSPATH=$CLASSPATH:lib/azure-keyvault-core-0.9.2.jar
CLASSPATH=$CLASSPATH:lib/azure-media-0.9.2.jar
CLASSPATH=$CLASSPATH:lib/azure-servicebus-0.9.2.jar
CLASSPATH=$CLASSPATH:lib/azure-serviceruntime-0.9.2.jar
CLASSPATH=$CLASSPATH:lib/azure-storage-4.0.0.jar
CLASSPATH=$CLASSPATH:lib/azure-svc-mgmt-0.9.2.jar
CLASSPATH=$CLASSPATH:lib/azure-svc-mgmt-compute-0.9.2.jar
CLASSPATH=$CLASSPATH:lib/azure-svc-mgmt-media-0.9.2.jar
CLASSPATH=$CLASSPATH:lib/azure-svc-mgmt-network-0.9.2.jar
CLASSPATH=$CLASSPATH:lib/azure-svc-mgmt-scheduler-0.9.2.jar
CLASSPATH=$CLASSPATH:lib/azure-svc-mgmt-sql-0.9.2.jar
CLASSPATH=$CLASSPATH:lib/azure-svc-mgmt-storage-0.9.2.jar
CLASSPATH=$CLASSPATH:lib/azure-svc-mgmt-websites-0.9.2.jar
CLASSPATH=$CLASSPATH:lib/bcprov-jdk15on-1.51.jar
CLASSPATH=$CLASSPATH:lib/commons-codec-1.10.jar
CLASSPATH=$CLASSPATH:lib/commons-io-2.4.jar
CLASSPATH=$CLASSPATH:lib/commons-lang-2.6.jar
CLASSPATH=$CLASSPATH:lib/commons-lang3-3.4.jar
CLASSPATH=$CLASSPATH:lib/commons-logging-1.1.3.jar
CLASSPATH=$CLASSPATH:lib/commons-net-3.3.jar
CLASSPATH=$CLASSPATH:lib/gson-2.2.4.jar
CLASSPATH=$CLASSPATH:lib/hamcrest-core-1.3.jar
CLASSPATH=$CLASSPATH:lib/httpclient-4.3.6.jar
CLASSPATH=$CLASSPATH:lib/httpcore-4.3.3.jar
CLASSPATH=$CLASSPATH:lib/jackson-annotations-2.6.0.jar
CLASSPATH=$CLASSPATH:lib/jackson-core-2.6.0.jar
CLASSPATH=$CLASSPATH:lib/jackson-core-asl-1.9.2.jar
CLASSPATH=$CLASSPATH:lib/jackson-databind-2.6.0.jar
CLASSPATH=$CLASSPATH:lib/jackson-jaxrs-1.9.2.jar
CLASSPATH=$CLASSPATH:lib/jackson-mapper-asl-1.9.2.jar
CLASSPATH=$CLASSPATH:lib/jackson-xc-1.9.2.jar
CLASSPATH=$CLASSPATH:lib/javax.inject-1.jar
CLASSPATH=$CLASSPATH:lib/jaxb-api-2.2.7.jar
CLASSPATH=$CLASSPATH:lib/jaxb-impl-2.2.3-1.jar
CLASSPATH=$CLASSPATH:lib/jcip-annotations-1.0.jar
CLASSPATH=$CLASSPATH:lib/jersey-client-1.13.jar
CLASSPATH=$CLASSPATH:lib/jersey-core-1.13.jar
CLASSPATH=$CLASSPATH:lib/jersey-json-1.13.jar
CLASSPATH=$CLASSPATH:lib/jettison-1.1.jar
CLASSPATH=$CLASSPATH:lib/jjwt-0.5.1.jar
CLASSPATH=$CLASSPATH:lib/json-20140107.jar
CLASSPATH=$CLASSPATH:lib/json-smart-1.1.1.jar
CLASSPATH=$CLASSPATH:lib/jsr311-api-1.1.1.jar
CLASSPATH=$CLASSPATH:lib/junit-4.11.jar
CLASSPATH=$CLASSPATH:lib/lang-tag-1.4.jar
CLASSPATH=$CLASSPATH:lib/log4j-1.2.17.jar
CLASSPATH=$CLASSPATH:lib/logkit-1.0.1.jar
CLASSPATH=$CLASSPATH:lib/mail-1.4.5.jar
CLASSPATH=$CLASSPATH:lib/nimbus-jose-jwt-3.1.2.jar
CLASSPATH=$CLASSPATH:lib/oauth2-oidc-sdk-4.5.jar
CLASSPATH=$CLASSPATH:lib/osgi_R4_core-1.0.jar
CLASSPATH=$CLASSPATH:lib/servlet-api-2.3.jar
CLASSPATH=$CLASSPATH:lib/slf4j-api-1.7.12.jar
CLASSPATH=$CLASSPATH:lib/stax-api-1.0.1.jar

export CLASSPATH

